apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.hub.externalSecret.name }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-rcc
    kind: ClusterSecretStore
  target:
    name: {{ .Values.hub.externalSecret.name }}
  data:
  - secretKey: JUPYTERHUB_CRYPT_KEY
    remoteRef:
      key: {{ .Values.hub.externalSecret.vaultPath }}
      property: JUPYTERHUB_CRYPT_KEY
