{{- if .Values.hub.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.hub.externalSecret.name }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-rcc
    kind: ClusterSecretStore
  target:
    name: {{ .Values.hub.externalSecret.name }}
  data:
{{- $root := . }}
{{- range .Values.hub.externalSecret.secretKeys }}
  - secretKey: "{{ . }}"
    remoteRef:
      key: {{ $root.Values.hub.externalSecret.vaultPath }}
      property: "{{ . }}"
{{- end }}
{{- end }}
